"use client";

import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import {
  ArrowRight,
  BarChart3,
  Building2,
  Car,
  Crown,
  FileText,
  Flag,
  Globe,
  Leaf,
  Lock,
  ShieldCheck,
  Sun,
  TrendingUp,
  Users,
  Zap,
} from "lucide-react";
import Footer from "@/components/Footer";

const FONT_STACK =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif";
const PRIMARY = "#05627C";
const ACCENT = "#3FA9C8";
const GOLD = "#F5CF0B";
const MINT = "#E8F5F0";

const roadmap = [
  {
    year: "2022",
    icon: Flag,
    title: "A Dream Takes Shape",
    desc: "Conceptualized Big Bull Energies as a bridge between renewable energy and financial solutions.",
  },
  {
    year: "2023",
    icon: Building2,
    title: "Laying the Foundation",
    desc: "Registered our website domain. Broke ground on our first solar plant.",
  },
  {
    year: "2024",
    icon: Zap,
    title: "A Year of Transformation",
    desc: "Completed first solar plant. Registered in New Zealand and the UK.",
  },
  {
    year: "2025",
    icon: Sun,
    title: "Global Expansion",
    desc: "Opened second plant in Groningen, Netherlands. Hosting global events.",
  },
  {
    year: "2026",
    icon: Leaf,
    title: "Pioneering the Future",
    desc: "Begin manufacturing EV and solar components. Expansion to 30+ countries.",
  },
  {
    year: "2027",
    icon: Car,
    title: "Smart Tech & Clean Mobility",
    desc: "Deploy AI-powered energy tracking. Launch EV Charging Stations.",
  },
  {
    year: "2028",
    icon: Crown,
    title: "Global Leader in Sustainable Finance & Energy",
    desc: "Operate 100+ solar plants worldwide. Fully integrated smart grids.",
    highlight: true,
  },
];

const missionFeatures = [
  {
    icon: Leaf,
    title: "Sustainable Investments",
    desc: "Focused on long-term value through renewable energy assets.",
  },
  {
    icon: BarChart3,
    title: "Diverse Energy Portfolio",
    desc: "Solar, wind, storage, and next-generation clean technologies.",
  },
  {
    icon: Users,
    title: "Community Impact",
    desc: "Partnering with local communities for shared prosperity.",
  },
  {
    icon: Globe,
    title: "A Greener Planet",
    desc: "Driving real change for a sustainable tomorrow worldwide.",
  },
];

const revenueCards = [
  {
    icon: Sun,
    title: "Solar Energy",
    value: "$9M+",
    suffix: "Annually",
    desc: "Generated by our solar farms",
  },
  {
    icon: Car,
    title: "EV Investments",
    value: "15%–35%",
    suffix: "Targeted Returns",
    desc: "Profit margins from EV and Forbes-listed investments",
  },
  {
    icon: TrendingUp,
    title: "Total Revenue",
    value: "$290M+",
    suffix: "Total projected asset under management by 2028",
    desc: "Yearly revenue with stable daily payouts of 1.5%–2.4% to users",
  },
];

function SectionWrap({ children }: { children: React.ReactNode }) {
  return (
    <div className="container mx-auto px-4 sm:px-6 lg:px-8">
      <div className="max-w-[1220px] mx-auto">{children}</div>
    </div>
  );
}

function PillBadge({
  children,
  variant = "light",
}: {
  children: React.ReactNode;
  variant?: "light" | "dark";
}) {
  return (
    <span
      className="inline-block text-[10px] sm:text-[11px] font-bold uppercase tracking-widest px-3 py-1.5 rounded-full mb-4 sm:mb-5"
      style={{
        backgroundColor: variant === "light" ? "#eef2f6" : "rgba(255,255,255,0.14)",
        color: variant === "light" ? PRIMARY : "rgba(255,255,255,0.9)",
      }}
    >
      {children}
    </span>
  );
}

function Tag({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex items-center gap-2 sm:gap-3 mb-3 sm:mb-4">
      <div className="h-px w-8 sm:w-10" style={{ backgroundColor: GOLD }} />
      <span
        className="text-[10px] sm:text-xs font-bold uppercase tracking-widest"
        style={{ color: PRIMARY }}
      >
        {children}
      </span>
    </div>
  );
}

function ArrowButton({
  href,
  label,
  variant = "gold",
}: {
  href: string;
  label: string;
  variant?: "gold" | "navy";
}) {
  const isGold = variant === "gold";
  return (
    <Link
      href={href}
      className="inline-flex items-center gap-3 font-bold px-5 sm:px-6 py-3 sm:py-3.5 text-[11px] sm:text-xs uppercase tracking-wide transition hover:opacity-90 rounded-lg"
      style={{
        backgroundColor: isGold ? GOLD : PRIMARY,
        color: isGold ? "#1a1a1a" : "#fff",
      }}
    >
      {label}
      <span
        className="w-7 h-7 sm:w-8 sm:h-8 rounded-full flex items-center justify-center flex-shrink-0"
        style={{
          backgroundColor: isGold ? PRIMARY : GOLD,
          color: isGold ? "#fff" : "#1a1a1a",
        }}
      >
        <ArrowRight className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
      </span>
    </Link>
  );
}

export default function AboutPage() {
  const [roadmapRevealed, setRoadmapRevealed] = useState(false);
  const roadmapRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const el = roadmapRef.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setRoadmapRevealed(true);
          observer.disconnect();
        }
      },
      { threshold: 0.15 },
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  return (
    <main
      className="min-h-screen w-full overflow-x-hidden pt-24 sm:pt-28 md:pt-32 lg:pt-[126px]"
      style={{ fontFamily: FONT_STACK }}
    >
      {/* Hero Section */}
      <section className="relative w-full overflow-hidden min-h-[420px] sm:min-h-[480px] md:min-h-[520px] lg:min-h-[560px] flex items-center">
        <Image
          src="/images/hero-emblem.png"
          alt="Big Bull Energies renewable energy landscape"
          fill
          priority
          className="object-cover object-center"
        />
        <div
          className="absolute inset-0 sm:hidden"
          style={{
            background:
              "linear-gradient(180deg, rgba(232,245,240,0.96) 0%, rgba(232,245,240,0.88) 50%, rgba(232,245,240,0.35) 100%)",
          }}
        />
        <div
          className="absolute inset-0 hidden sm:block"
          style={{
            background:
              "linear-gradient(90deg, rgba(232,245,240,0.97) 0%, rgba(232,245,240,0.88) 28%, rgba(232,245,240,0.45) 45%, rgba(232,245,240,0.05) 58%, transparent 70%)",
          }}
        />
        <SectionWrap>
          <div className="relative z-10 max-w-xl py-8 sm:py-10">
            <Tag>Who We Are</Tag>
            <h1
              className="text-2xl sm:text-3xl md:text-4xl lg:text-[2.75rem] font-extrabold leading-tight mb-3 sm:mb-4"
              style={{ color: PRIMARY }}
            >
              Empowering investors through innovative binary systems and
              sustainable energy
            </h1>
            <p
              className="text-xs sm:text-sm md:text-base leading-relaxed mb-5 sm:mb-6"
              style={{ color: PRIMARY, opacity: 0.75 }}
            >
              We are building a diversified renewable energy portfolio that
              bridges sustainable infrastructure with transparent financial
              growth — empowering investors to earn while powering a cleaner
              tomorrow.
            </p>
            <ArrowButton href="#founding-vision" label="Discover Our Vision" />
          </div>
        </SectionWrap>
      </section>

      {/* Who We Are + Founding Vision + Approach */}
      <section
        id="founding-vision"
        className="relative w-full bg-white py-10 sm:py-12 md:py-16 lg:py-20 overflow-hidden"
      >
        <SectionWrap>
          {/* Top row — equal height cards */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-5 sm:gap-6 lg:gap-8 lg:items-stretch">
            {/* WHO WE ARE card */}
            <div
              className="rounded-2xl sm:rounded-3xl p-6 sm:p-8 md:p-10 shadow-[0_8px_30px_rgba(5,98,124,0.08)] h-full flex flex-col justify-center"
              style={{ backgroundColor: "#fff" }}
            >
              <PillBadge>Who We Are</PillBadge>
              <h2
                className="text-2xl sm:text-3xl md:text-[2rem] font-bold leading-snug mb-4 sm:mb-5"
                style={{ color: PRIMARY }}
              >
                Driving change through clean energy solutions
              </h2>
              <p
                className="text-sm sm:text-base leading-relaxed mb-6 sm:mb-8"
                style={{ color: "#64748b" }}
              >
                We are a forward-thinking investment and development firm
                focused on renewable energy projects that generate sustainable
                returns and real-world impact.
              </p>
              <Link
                href="/who-we-are/leadership"
                className="inline-flex items-center gap-2.5 font-bold px-6 sm:px-7 py-3 sm:py-3.5 text-xs uppercase tracking-wide rounded-full text-white transition hover:opacity-90 w-fit"
                style={{ backgroundColor: PRIMARY }}
              >
                Learn More
                <ArrowRight className="w-4 h-4" />
              </Link>
            </div>

            {/* Founding Vision — image left, text right on dark card */}
            <div
              className="rounded-2xl sm:rounded-3xl overflow-hidden shadow-[0_8px_30px_rgba(5,98,124,0.12)] flex flex-col sm:flex-row min-h-[300px] lg:min-h-[340px]"
              style={{ backgroundColor: "#083544" }}
            >
              <div className="relative w-full sm:w-[52%] min-h-[220px] sm:min-h-0 flex-shrink-0">
                <Image
                  src="/images/founding-vision.png"
                  alt="Big Bull Energies founding vision presentation"
                  fill
                  className="object-cover object-left"
                />
              </div>
              <div className="flex flex-col justify-between p-6 sm:p-7 md:p-8 flex-1 bg-[#083544]">
                <div>
                  <h3 className="text-xl sm:text-2xl font-bold text-white mb-3 sm:mb-4 leading-snug">
                    Our Founding Vision
                  </h3>
                  <p className="text-sm leading-relaxed text-white/70">
                    Founded with a vision to accelerate the global transition to
                    clean energy, we partner with landowners, investors, and
                    communities to develop solar, wind, and storage projects that
                    deliver long-term value and a cleaner planet for generations
                    to come.
                  </p>
                </div>
                <Link
                  href="/our-plan"
                  className="mt-6 w-10 h-10 sm:w-11 sm:h-11 rounded-full flex items-center justify-center self-end transition hover:scale-110"
                  style={{ backgroundColor: ACCENT }}
                  aria-label="Explore our plan"
                >
                  <ArrowRight className="w-4 h-4 sm:w-5 sm:h-5 text-white" />
                </Link>
              </div>
            </div>
          </div>

          {/* Our Approach — unified split card */}
          <div className="mt-6 sm:mt-8 lg:mt-10 rounded-2xl sm:rounded-3xl overflow-hidden shadow-[0_16px_48px_rgba(5,98,124,0.12)] border border-slate-100">
            <div className="grid grid-cols-1 lg:grid-cols-2">
              {/* Left — content */}
              <div
                className="relative p-7 sm:p-9 md:p-10 lg:p-12 flex flex-col justify-center min-h-[380px] sm:min-h-[440px] lg:min-h-[480px]"
                style={{
                  background: "linear-gradient(145deg, #05627C 0%, #044a5c 55%, #033d4d 100%)",
                }}
              >
                <ShieldCheck
                  className="absolute right-6 bottom-6 w-40 h-40 sm:w-48 sm:h-48 opacity-[0.06] text-white pointer-events-none"
                  strokeWidth={0.75}
                />
                <div className="relative z-10 max-w-lg">
                  <PillBadge variant="dark">Our Approach</PillBadge>
                  <h2 className="text-2xl sm:text-3xl md:text-[2rem] font-bold leading-snug mb-4 text-white">
                    Security and transparency in everything we do
                  </h2>
                  <p className="text-sm sm:text-base leading-relaxed mb-8 text-white/75">
                    We invest in a diverse range of renewable energy technologies
                    to minimize risk and maximize long-term returns for our
                    investors and partners.
                  </p>
                  <Link
                    href="/our-plan"
                    className="inline-flex items-center gap-3 font-bold pl-6 pr-2 py-2.5 text-xs uppercase tracking-wide rounded-full transition hover:brightness-105 w-fit"
                    style={{ backgroundColor: GOLD, color: "#1a1a1a" }}
                  >
                    Explore Our Plan
                    <span className="w-10 h-10 rounded-full flex items-center justify-center bg-white shadow-md">
                      <ArrowRight className="w-4 h-4" style={{ color: PRIMARY }} />
                    </span>
                  </Link>
                </div>
              </div>

              {/* Right — circle graphic */}
              <div
                className="relative flex items-center justify-center min-h-[380px] sm:min-h-[440px] lg:min-h-[480px] overflow-hidden py-8 sm:py-10"
                style={{ backgroundColor: "#f0f6f8" }}
              >
                {/* Dot grid */}
                <div
                  className="absolute inset-0 opacity-70"
                  style={{
                    backgroundImage:
                      "radial-gradient(circle, rgba(5,98,124,0.14) 1.5px, transparent 1.5px)",
                    backgroundSize: "18px 18px",
                  }}
                />
                {/* Soft glow behind circle */}
                <div
                  className="absolute w-80 h-80 sm:w-96 sm:h-96 rounded-full blur-3xl opacity-40"
                  style={{ backgroundColor: ACCENT }}
                />

                <div className="relative w-[300px] h-[300px] sm:w-[360px] sm:h-[360px] md:w-[400px] md:h-[400px]">
                  {/* Subtle static ring */}
                  <div
                    className="absolute inset-0 rounded-full border border-dashed pointer-events-none opacity-30"
                    style={{ borderColor: "rgba(5,98,124,0.25)" }}
                  />

                  {/* Main photo circle */}
                  <div className="absolute inset-3 sm:inset-4 z-10">
                    <div className="relative w-full h-full rounded-full overflow-hidden border-[6px] sm:border-[7px] border-white shadow-[0_20px_48px_rgba(5,98,124,0.22)]">
                      <Image
                        src="/images/img4.webp"
                        alt="Solar farm landscape"
                        fill
                        className="object-cover"
                        sizes="(max-width: 640px) 300px, 400px"
                      />
                    </div>
                  </div>

                  {/* Lock icon — left, overlapping circle edge */}
                  <div className="absolute left-0 top-[38%] z-20 -translate-x-1/4">
                    <div
                      className="w-20 h-20 sm:w-24 sm:h-24 rounded-full flex items-center justify-center shadow-[0_12px_32px_rgba(5,98,124,0.2)] border-[3px] border-white"
                      style={{ backgroundColor: "#fff" }}
                    >
                      <Lock className="w-8 h-8 sm:w-9 sm:h-9" style={{ color: PRIMARY }} />
                    </div>
                  </div>

                  {/* Document + shield icon — right, overlapping circle edge */}
                  <div className="absolute right-0 top-[42%] z-20 translate-x-1/4">
                    <div
                      className="relative w-20 h-20 sm:w-24 sm:h-24 rounded-full flex items-center justify-center shadow-[0_12px_32px_rgba(5,98,124,0.2)] border-[3px] border-white"
                      style={{ backgroundColor: "#fff" }}
                    >
                      <FileText className="w-7 h-7 sm:w-8 sm:h-8" style={{ color: PRIMARY }} />
                      <div
                        className="absolute -bottom-0.5 -right-0.5 w-7 h-7 rounded-full flex items-center justify-center border-2 border-white"
                        style={{ backgroundColor: ACCENT }}
                      >
                        <ShieldCheck className="w-3.5 h-3.5 text-white" strokeWidth={3} />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </SectionWrap>
      </section>

      {/* Mission Section — about1.png background */}
      <section className="relative w-full py-14 sm:py-16 md:py-20 lg:py-24 overflow-hidden">
        <Image
          src="/images/about1.png"
          alt="Renewable energy landscape with solar, wind, and storage"
          fill
          className="object-cover object-center"
        />
        <div
          className="absolute inset-0"
          style={{
            background:
              "linear-gradient(90deg, rgba(5,98,124,0.94) 0%, rgba(5,98,124,0.88) 45%, rgba(5,98,124,0.55) 70%, rgba(5,98,124,0.25) 100%)",
          }}
        />
        <SectionWrap>
          <div className="relative z-10">
            <div className="text-center mb-10 sm:mb-12 md:mb-14 max-w-3xl mx-auto">
              <div
                className="w-12 h-12 sm:w-14 sm:h-14 rounded-full flex items-center justify-center mx-auto mb-4 sm:mb-5 border border-white/20"
                style={{ backgroundColor: "rgba(255,255,255,0.1)" }}
              >
                <ShieldCheck className="w-6 h-6 sm:w-7 sm:h-7 text-white" />
              </div>
              <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-white mb-3 sm:mb-4 leading-tight">
                Our Mission is to Power a Better Tomorrow
              </h2>
              <p className="text-sm sm:text-base leading-relaxed text-white/75">
                We believe that sustainable energy and transparent financial
                systems can work together to create lasting value for investors
                and communities worldwide.
              </p>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-5 md:gap-6">
              {missionFeatures.map(({ icon: Icon, title, desc }) => (
                <div
                  key={title}
                  className="rounded-2xl p-5 sm:p-6 text-center backdrop-blur-sm border border-white/10"
                  style={{ backgroundColor: "rgba(255,255,255,0.07)" }}
                >
                  <div
                    className="w-11 h-11 sm:w-12 sm:h-12 rounded-full flex items-center justify-center mx-auto mb-3 sm:mb-4"
                    style={{ backgroundColor: "rgba(245,207,11,0.15)" }}
                  >
                    <Icon className="w-5 h-5 sm:w-6 sm:h-6" style={{ color: GOLD }} />
                  </div>
                  <h3 className="text-sm sm:text-base font-bold text-white mb-2">
                    {title}
                  </h3>
                  <p className="text-[11px] sm:text-xs leading-relaxed text-white/65">
                    {desc}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </SectionWrap>
      </section>

      {/* Roadmap Section */}
      <section className="relative w-full bg-white py-10 sm:py-12 md:py-16 lg:py-20">
        <SectionWrap>
          <div className="text-center mb-8 sm:mb-10 md:mb-14">
            <div className="flex justify-center">
              <PillBadge>Our Journey</PillBadge>
            </div>
            <h2
              className="text-xl sm:text-2xl md:text-3xl lg:text-4xl font-bold -mt-2"
              style={{ color: PRIMARY }}
            >
              Big Bull Energies Roadmap (2022 – 2028)
            </h2>
          </div>

          <div ref={roadmapRef} className="relative overflow-x-auto pb-4">
            <div className="relative min-w-[900px] sm:min-w-[1000px] lg:min-w-0">
              <div
                className="absolute left-0 right-0 top-[1.65rem] sm:top-[1.85rem] h-0.5"
                style={{ backgroundColor: "rgba(5,98,124,0.2)" }}
              />
              <div className="relative grid grid-cols-7 gap-2 sm:gap-3">
                {roadmap.map((step, i) => {
                  const Icon = step.icon;
                  const isHighlight = step.highlight;
                  return (
                    <div
                      key={step.year}
                      className="flex flex-col items-center text-center transition-all duration-700 ease-out"
                      style={{
                        opacity: roadmapRevealed ? 1 : 0,
                        transform: roadmapRevealed ? "translateY(0)" : "translateY(16px)",
                        transitionDelay: `${i * 120}ms`,
                      }}
                    >
                      <div
                        className="w-11 h-11 sm:w-12 sm:h-12 md:w-14 md:h-14 rounded-full flex items-center justify-center mb-2 sm:mb-3 relative z-10 shadow-sm"
                        style={{
                          backgroundColor: isHighlight ? PRIMARY : "#fff",
                          border: isHighlight ? "none" : `2px solid ${PRIMARY}33`,
                          boxShadow: isHighlight ? "0 4px 16px rgba(5,98,124,0.3)" : undefined,
                        }}
                      >
                        <Icon
                          className="w-5 h-5 sm:w-6 sm:h-6"
                          style={{ color: isHighlight ? "#fff" : PRIMARY }}
                        />
                      </div>
                      <span
                        className="text-xs sm:text-sm font-bold mb-2 sm:mb-3"
                        style={{ color: PRIMARY }}
                      >
                        {step.year}
                      </span>
                      <div
                        className="rounded-xl p-3 sm:p-4 w-full min-h-[130px] sm:min-h-[150px] flex flex-col"
                        style={{
                          backgroundColor: isHighlight ? PRIMARY : "#fff",
                          border: isHighlight ? "none" : "1px solid rgba(5,98,124,0.12)",
                          boxShadow: isHighlight
                            ? "0 8px 24px rgba(5,98,124,0.25)"
                            : "0 4px 16px rgba(5,98,124,0.07)",
                        }}
                      >
                        <h3
                          className="text-[11px] sm:text-xs md:text-sm font-bold mb-1.5 sm:mb-2 leading-snug"
                          style={{ color: isHighlight ? "#fff" : PRIMARY }}
                        >
                          {step.title}
                        </h3>
                        <p
                          className="text-[10px] sm:text-[11px] leading-snug flex-1"
                          style={{ color: isHighlight ? "rgba(255,255,255,0.8)" : `${PRIMARY}AA` }}
                        >
                          {step.desc}
                        </p>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </SectionWrap>
      </section>

      {/* Revenue Model Section */}
      <section className="relative w-full bg-white py-10 sm:py-12 md:py-16 lg:py-20">
        <SectionWrap>
          <h2
            className="text-xl sm:text-2xl md:text-3xl lg:text-4xl font-bold mb-8 sm:mb-10 md:mb-12 text-center"
            style={{ color: PRIMARY }}
          >
            Our Diversified Revenue Model
          </h2>

          {/* Elevated stage platform */}
          <div
            className="relative rounded-[1.75rem] p-6 sm:p-8 md:p-10 lg:p-12"
            style={{
              backgroundColor: "#fff",
              boxShadow: "0 24px 60px -12px rgba(5,98,124,0.12), 0 0 0 1px rgba(5,98,124,0.06)",
            }}
          >
            <div className="grid grid-cols-1 md:grid-cols-3 gap-5 sm:gap-6 lg:gap-8">
              {revenueCards.map(({ icon: Icon, title, value, suffix, desc }) => (
                <div
                  key={title}
                  className="rounded-2xl p-5 sm:p-6 md:p-8 text-center"
                  style={{
                    backgroundColor: "#fff",
                    boxShadow: "0 8px 32px rgba(5,98,124,0.1)",
                  }}
                >
                  <div
                    className="w-12 h-12 sm:w-14 sm:h-14 rounded-full flex items-center justify-center mx-auto mb-4 sm:mb-5"
                    style={{ backgroundColor: MINT }}
                  >
                    <Icon className="w-6 h-6 sm:w-7 sm:h-7" style={{ color: PRIMARY }} />
                  </div>
                  <h3
                    className="text-base sm:text-lg font-bold mb-3 sm:mb-4"
                    style={{ color: PRIMARY }}
                  >
                    {title}
                  </h3>
                  <div className="h-px mb-3 sm:mb-4 mx-auto w-12" style={{ backgroundColor: PRIMARY, opacity: 0.2 }} />
                  <div
                    className="text-3xl sm:text-4xl md:text-[2.75rem] font-bold mb-1 leading-none"
                    style={{ color: GOLD }}
                  >
                    {value}
                  </div>
                  <p
                    className="text-xs sm:text-sm font-semibold mb-2 sm:mb-3 mt-2"
                    style={{ color: PRIMARY, opacity: 0.7 }}
                  >
                    {suffix}
                  </p>
                  <p
                    className="text-[11px] sm:text-xs leading-relaxed"
                    style={{ color: PRIMARY, opacity: 0.55 }}
                  >
                    {desc}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </SectionWrap>
      </section>

      {/* CTA Section */}
      <section className="relative w-full overflow-hidden min-h-[420px] sm:min-h-[480px] lg:min-h-[560px] flex items-center">
        {/* Background */}
        <Image
          src="/images/solar-sunset.png"
          alt="Solar farm and wind turbines at sunset"
          fill
          priority
          className="object-cover"
        />

        {/* Mobile Overlay */}
        <div
          className="absolute inset-0 sm:hidden"
          style={{
            background:
              "linear-gradient(180deg, rgba(248,252,254,0.95) 0%, rgba(248,252,254,0.82) 45%, rgba(248,252,254,0.35) 100%)",
          }}
        />

        {/* Desktop Overlay */}
        <div
          className="absolute inset-0 hidden sm:block"
          style={{
            background:
              "linear-gradient(90deg, rgba(248,252,254,0.96) 0%, rgba(248,252,254,0.88) 28%, rgba(248,252,254,0.52) 52%, rgba(248,252,254,0.12) 75%, rgba(248,252,254,0) 100%)",
          }}
        />

        <SectionWrap>
          <div className="relative z-10 flex items-center min-h-[420px] sm:min-h-[480px] lg:min-h-[560px]">

            <div className="max-w-2xl">

              {/* Badge */}
              <div className="flex items-center gap-3 mb-6">
                <span
                  className="w-12 h-[2px]"
                  style={{ backgroundColor: GOLD }}
                />
                <span
                  className="text-xs font-bold uppercase tracking-[0.3em]"
                  style={{ color: PRIMARY }}
                >
                  Build The Future
                </span>
              </div>

              {/* Heading */}
              <h2
                className="text-3xl sm:text-4xl lg:text-5xl xl:text-6xl font-bold leading-[1.1] mb-6"
                style={{ color: PRIMARY }}
              >
                Join us in building
                <br />
                the{" "}
                <span style={{ color: ACCENT }}>
                  energy future
                </span>
              </h2>

              {/* Description */}
              <p
                className="max-w-xl text-base lg:text-lg leading-8 mb-10"
                style={{ color: "#475569" }}
              >
                Be part of a sustainable tomorrow by investing in renewable
                energy solutions. Grow your wealth while contributing to a
                cleaner and greener future with Big Bull Energies.
              </p>

              {/* Buttons */}
              <div className="flex flex-wrap gap-4">

                <Link
                  href="/careers"
                  className="inline-flex items-center gap-2 rounded-xl px-8 py-4 font-semibold transition-all duration-300 hover:-translate-y-1 hover:shadow-xl"
                  style={{
                    backgroundColor: GOLD,
                    color: "#111827",
                  }}
                >
                  View Careers
                  <ArrowRight className="w-5 h-5" />
                </Link>

                <Link
                  href="/contact"
                  className="inline-flex items-center gap-2 rounded-xl px-8 py-4 font-semibold transition-all duration-300 hover:bg-white"
                  style={{
                    color: PRIMARY,
                    border: `1px solid ${PRIMARY}`,
                    background: "rgba(255,255,255,0.45)",
                    backdropFilter: "blur(14px)",
                  }}
                >
                  Contact Us
                </Link>

              </div>

            </div>

          </div>
        </SectionWrap>
      </section>

      <Footer />
    </main>
  );
}
